### ISSUE TITLE
Add a readme?

### ISSUE THREAD

**Issue by o-jasper** [Qwertymine/aquarium_glass#1]
Can pretty much use the [forum post](https://forum.minetest.net/viewtopic.php?f=9&t=14491&view=unread#p215158).

Whats the rendering issue?

**Comment by Qwertymine** [comment]
Liquid rendering generates the mesh for large bodies of liquids in large 'blocks' (IDK the correct terminology) .
When looking at the water surface from below, depending on the angle, the game engine will not render these blocks.

This means that from some angles, the water surface is not rendered. From some angles it is rendered. And from most angles each 'block' changes whether is is rendered or not multiple times a second.

**Comment by Qwertymine** [comment]
This should clarify what I'm saying:
![Missing Areas of Water, Some areas are missing](http://i.imgur.com/PKnSilU.png)

In-game, the bottom left 3 missing blocks are flickering consistently, and most of the rest render for 1 frame per second.
